"""
Canonical MLP brain-age regressor used in the paper.

Architecture (one hidden layer)
-------------------------------
Linear(input_size, hidden_size) -> BatchNorm1d -> ReLU -> Dropout(p=dropout)
-> Linear(hidden_size, 1)

The forward pass returns the raw logit; training/prediction code applies a
sigmoid and rescales it to the [y_lower, y_lower + y_span] age range.

Training (per supplement, "Machine learning model"):
  * Loss: Smooth-L1 (Huber, beta=3) with an L1 weight penalty (lambda=1e-3).
  * Optimiser: Adam(lr, weight_decay) + ReduceLROnPlateau(factor=0.5, patience=5).
  * Early stopping: epoch - val_improve_epoch >= patience triggers a break.

Caller signature is fixed by ``src.utils.train_utils.execute_in_val_and_test_NN``:

    regressor.fit(
        Xtrain, ytrain, Xval, yval,
        fold, input_size, hidden_size,
        lr=2e-4, weight_decay=1e-3, dropout=0.35,
        patience=10, batch_size=128,
    )
    regressor.predict(X)
"""

import os
import random
from typing import List, Sequence, Union

import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

torch.manual_seed(0)
np.random.seed(0)
random.seed(0)


def eval_huber(model, X, y, y_span, y_lower, beta=3):
    """Return Smooth-L1 (Huber) loss over a full tensor."""
    huber = nn.SmoothL1Loss(beta=beta)
    with torch.no_grad():
        y_pred = torch.sigmoid(model(X)).squeeze() * y_span + y_lower
        loss = huber(y, y_pred)
    return loss.item()


class Dataset(torch.utils.data.Dataset):
    """Wraps (x, y, w). If ``w`` is None, ``__getitem__`` returns (x, y)."""

    def __init__(self, x, y, w=None):
        self.x = torch.as_tensor(x, dtype=torch.float32)
        self.y = torch.as_tensor(y, dtype=torch.float32)
        self.w = None if w is None else torch.as_tensor(w, dtype=torch.float32)

    def __len__(self):
        return self.x.shape[0]

    def __getitem__(self, idx):
        if self.w is None:
            return self.x[idx], self.y[idx]
        return self.x[idx], self.y[idx], self.w[idx]


class PerceptronFunnel(nn.Module):
    """
    Funnel-shaped multilayer perceptron (specialised here to a single hidden
    layer, matching the published model).

    Parameters
    ----------
    input_size : int
        Number of input features.
    hidden_sizes : int | Sequence[int]
        * Sequence -> explicit hidden-layer sizes (e.g. ``[128, 64, 32]``).
        * Integer  -> initial size; subsequent layers are generated by halving
          until ``min_hidden`` is reached.
    dropout_prob : float
        Dropout probability applied after every hidden layer.
    min_hidden : int
        Minimum hidden width when auto-generating the funnel.
    batch_norm : bool
        Insert ``nn.BatchNorm1d`` after every hidden layer.
    """

    def __init__(
        self,
        input_size: int,
        hidden_sizes: Union[int, Sequence[int]],
        dropout_prob: float = 0.3,
        min_hidden: int = 8,
        batch_norm: bool = True,
    ):
        super().__init__()

        # 1. Build the list of hidden-layer sizes
        if isinstance(hidden_sizes, int):
            sizes: List[int] = []
            h = hidden_sizes
            while h >= min_hidden:
                sizes.append(h)
                h //= 2
            hidden_sizes = sizes

        if len(hidden_sizes) == 0:
            raise ValueError("`hidden_sizes` must contain at least one value.")

        # 2. Stack the layers
        layers = []
        in_features = input_size
        for out_features in hidden_sizes:
            layers.append(nn.Linear(in_features, out_features))
            if batch_norm:
                layers.append(nn.BatchNorm1d(out_features))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(p=dropout_prob))
            in_features = out_features

        # Regression read-out
        layers.append(nn.Linear(in_features, 1))
        self.network = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.network(x)

    def init_params(self):
        for m in self.modules():
            if hasattr(m, "reset_parameters"):
                m.reset_parameters()


class Perceptron:
    """Wrapper that owns the optimiser, scheduler and training loop."""

    def __init__(self, epochs=100):
        self.model = None
        self.epochs = epochs
        self.epoch = 0

    def fit(
        self,
        Xtrain, ytrain, Xval, yval,
        fold, input_size, hidden_size,
        lr=0.01, weight_decay=1e-4, dropout=0.5,
        pretrained_model_path=None,
        patience=10, patience_lr=5,
        batch_size=16, save_dir=None,
    ):
        X_val = torch.tensor(Xval).float()
        y_val = torch.tensor(yval).float()
        X = torch.tensor(Xtrain).float()
        y = torch.tensor(ytrain).float()

        self.y_span = max(y) - min(y)
        self.y_lower = min(y)

        if self.model is None:
            model = PerceptronFunnel(
                input_size=input_size,
                hidden_sizes=[hidden_size],
                dropout_prob=dropout,
            )
            if pretrained_model_path:
                model.load_state_dict(torch.load(pretrained_model_path))
                print(f"Loaded pretrained model from {pretrained_model_path}")
            else:
                model.init_params()
            self.model = model

        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='min', factor=0.5, patience=5,
        )

        criterion = nn.SmoothL1Loss(beta=3)
        l1_lambda = 1e-3

        best_epoch = 0
        best_mae_val = np.inf
        best_mae_train = np.inf
        best_mae_train_eval = np.inf
        best_model = model
        val_improve_epoch = 0
        total_updates = 0

        train_loss_list, val_loss_list, epoch_list = [], [], []

        for epoch in range(self.epochs):
            model.train()
            train_dataset = Dataset(X, y)
            train_loader = torch.utils.data.DataLoader(
                dataset=train_dataset,
                batch_size=int(X.shape[0] / batch_size),
                drop_last=True,
            )

            running_loss = 0.0       # accumulated loss weighted by batch size
            running_samples = 0      # total samples seen this epoch

            for x_b, y_b in train_loader:
                y_pred = torch.sigmoid(model(x_b)).squeeze() * self.y_span + self.y_lower
                per_sample = criterion(y_pred.reshape(-1, 1), y_b.reshape(-1, 1)).squeeze()

                # L1 regularisation on weight matrices
                l1_norm = sum(
                    p.abs().sum()
                    for name, p in model.named_parameters()
                    if 'weight' in name
                )
                loss = per_sample.mean() + l1_lambda * l1_norm

                running_loss += loss.item() * x_b.size(0)
                running_samples += x_b.size(0)

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                total_updates += 1

            # Validation
            model.eval()
            with torch.no_grad():
                val_loss_eval = eval_huber(model, X_val, y_val, self.y_span, self.y_lower, beta=3)
                train_loss_eval = eval_huber(model, X, y, self.y_span, self.y_lower, beta=3)

            scheduler.step(val_loss_eval)

            # Track best model (note: best_model and self.model alias the same
            # Python object — weights mutate in place across epochs)
            if val_loss_eval < best_mae_val:
                best_mae_val = val_loss_eval
                best_mae_train_eval = train_loss_eval
                best_mae_train = running_loss / running_samples
                best_model = model
                best_epoch = epoch
                val_improve_epoch = epoch

            # Early stopping
            if epoch - val_improve_epoch >= patience:
                break

            epoch_list.append(epoch)
            train_loss_list.append(running_loss / running_samples)
            val_loss_list.append(val_loss_eval)

            print('model, epoch: {}, train_loss: {:.4f}, val_loss: {:.4f}'.format(
                epoch, running_loss / running_samples, val_loss_eval))

        # Loss curve
        plt.figure(figsize=(10, 6))
        plt.plot(epoch_list, train_loss_list, label='Training Loss', color='blue')
        plt.plot(epoch_list, val_loss_list, label='Validation Loss', color='red')
        plt.title('Training and Validation Loss Over Epochs')
        plt.xlabel('Epochs')
        plt.ylabel('Loss')
        plt.legend()
        plt.grid(True)

        plot_filename = f'training_validation_loss_{fold}.svg'
        if save_dir is not None:
            os.makedirs(save_dir, exist_ok=True)
            plot_path = os.path.join(save_dir, plot_filename)
        else:
            plot_path = plot_filename
        plt.savefig(plot_path)
        plt.close()

        print(
            f"No improvement in validation in the last {patience} epochs, "
            f"returning best model (epoch {best_epoch}) with "
            f"best_mae_val: {best_mae_val:.4f}, "
            f"mae_train: {best_mae_train:.4f}, "
            f"mae_train_eval: {best_mae_train_eval:.4f}"
        )
        return best_model

    def predict(self, X):
        X = torch.tensor(X).float()
        self.model.eval()
        with torch.no_grad():
            result = torch.sigmoid(self.model(X).squeeze()) * self.y_span + self.y_lower
        return result.cpu().detach().numpy().squeeze()
